apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: quay-solver-data
  namespace: quay-solver
  labels:
    app.kubernetes.io/name: quay-solver
spec:
  accessModes:
    - ReadWriteOnce
  # k3s incluye local-path-provisioner por defecto
  storageClassName: local-path
  resources:
    requests:
      storage: 500Mi
